name: Call Gemini API on PR

on:
  pull_request:
    types: [opened]

jobs:
  ask-gemini:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Call Gemini API with prompt
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "📡 Calling Gemini API..."

          PROMPT="Write a documentation for this PR."

          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=${GEMINI_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @- <<EOF
{
  "contents": [
    {
      "parts": [
        { "text": "${PROMPT}" }
      ]
    }
  ]
}
EOF
)

          echo "🧠 Gemini API Response:"
          echo "$RESPONSE"